permalink: /posts/:title
markdown: kramdown
  
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

name: KTH
url: daniellsm.github.io
enforce_ssl: daniellsm.github.io
description: Daniel's personal website

collections:
  ml:
    output: true
  math:
    output: true

defaults:
  - scope:
      path: ""
      type: ml
    values:
      layout: post
  - scope:
      path: ""
      type: math
    values:
      layout: post
